'use strict';
const $=id=>document.getElementById(id), C=299792458;let data=[];
function num(id,d,min=-Infinity,max=Infinity){let v=parseFloat($(id).value);if(!Number.isFinite(v))v=d;return Math.max(min,Math.min(max,v))}
function fmtF(f){return f<1?(f*1000).toFixed(0)+' kHz':f.toFixed(f<10?2:1)+' MHz'}
function dbuv(v){return 20*Math.log10(Math.max(v,1e-18)/1e-6)}
function ui(){let sh=$('shield').value==='yes',zt=$('method').value==='zt';$('shieldSec').classList.toggle('off',!sh);$('method').disabled=!sh;$('attWrap').classList.toggle('hide',zt);$('ztWrap').classList.toggle('hide',!zt);$('bciWrap').classList.toggle('hide',!zt);$('ishWrap').classList.toggle('hide',!zt||$('useBci').checked);$('limWrap').classList.toggle('hide',$('cmode').value!=='known')}
function calculate(){ui();let I=num('I',100,0)/1000,Z=num('Z',50,.001),f0=num('f0',.25,.001),f1=num('f1',200,.002),N=Math.round(num('np',1000,20,5000)),L=num('L',1,.01),vf=num('vf',.7,.1,1),sh=$('shield').value==='yes',method=$('method').value,att=num('att',12,0),zt=num('zt',10,0)/1000,ish=$('useBci').checked?I:num('ish',100,0)/1000,conn=num('conn',0,0),fil=num('filter',20,0),log=$('scale').value==='log';if(f1<=f0){f1=f0*2;$('f1').value=f1}let fq=C*vf/(4*L)/1e6;$('qtr').textContent=fmtF(fq);data=[];for(let i=0;i<N;i++){let u=i/(N-1),f=log?f0*Math.pow(f1/f0,u):f0+(f1-f0)*u;let r=.12+.88*Math.abs(Math.sin(2*Math.PI*f*1e6*L/(C*vf)));let v0=I*Z*r;let v1=!sh?v0:(method==='zt'?zt*ish*L*r:v0*Math.pow(10,-att/20));let v=v1*Math.pow(10,-(conn+fil)/20);data.push({f,v,db:dbuv(v)})}let worst=data.reduce((a,b)=>b.db>a.db?b:a);$('max').textContent=worst.db.toFixed(1)+' dBµV';$('crit').textContent=(fq>=f0&&fq<=f1)?fmtF(fq):'hors bande';if($('cmode').value==='known'){let lim=dbuv(num('limit',10,.000001)/1000);$('margin').textContent=(lim-worst.db).toFixed(1)+' dB'}else $('margin').textContent='non calculée';draw(f0,f1,log,L,vf);$('diag').textContent='Moteur actif • '+N+' points calculés';$('diag').classList.add('ready')}
function draw(f0,f1,log,L,vf){let S=$('chart'),W=1000,H=420,l=75,r=25,t=25,b=60,pw=W-l-r,ph=H-t-b,mn=Infinity,mx=-Infinity;data.forEach(d=>{mn=Math.min(mn,d.db);mx=Math.max(mx,d.db)});mn=Math.floor((mn-10)/20)*20;mx=Math.ceil((mx+10)/20)*20;if(mx<=mn)mx=mn+40;let X=f=>l+(log?Math.log(f/f0)/Math.log(f1/f0):(f-f0)/(f1-f0))*pw,Y=v=>t+(mx-v)/(mx-mn)*ph,h=`<rect x="${l}" y="${t}" width="${pw}" height="${ph}" fill="white" stroke="#9aa5af"/>`;for(let v=mn;v<=mx;v+=20){let y=Y(v);h+=`<line x1="${l}" x2="${W-r}" y1="${y}" y2="${y}" stroke="#dde2e6"/><text x="${l-8}" y="${y+4}" text-anchor="end" font-size="11">${v}</text>`}let q=C*vf/(4*L)/1e6;for(let k=0;k<80;k++){let f=(2*k+1)*q;if(f>f1)break;if(f>=f0){let x=X(f);h+=`<line x1="${x}" x2="${x}" y1="${t}" y2="${t+ph}" stroke="#a45b00" stroke-dasharray="5 5" opacity=".55"/>`}}h+=`<polyline points="${data.map(d=>X(d.f).toFixed(1)+','+Y(d.db).toFixed(1)).join(' ')}" fill="none" stroke="#1268a8" stroke-width="2.5"/>`;[0,.25,.5,.75,1].forEach(q=>{let f=log?f0*Math.pow(f1/f0,q):f0+(f1-f0)*q;h+=`<text x="${X(f)}" y="${H-32}" text-anchor="middle" font-size="11">${fmtF(f)}</text>`});h+=`<text x="${l+pw/2}" y="${H-8}" text-anchor="middle" font-size="13">Fréquence</text><text x="17" y="${t+ph/2}" text-anchor="middle" transform="rotate(-90 17 ${t+ph/2})" font-size="13">Niveau carte (dBµV)</text>`;S.innerHTML=h}
$('calc').addEventListener('click',calculate);$('reset').addEventListener('click',()=>{location.reload()});['shield','method','useBci','cmode'].forEach(id=>$(id).addEventListener('change',ui));$('client').addEventListener('click',()=>alert('Fiche client : module PDF à activer après validation du moteur sur ton iPhone.'));window.addEventListener('error',e=>{$('diag').textContent='Erreur : '+e.message;$('diag').classList.remove('ready')});ui();calculate();
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}))}
